# Generated by Django 3.2.4 on 2021-06-06 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210607_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='date',
        ),
    ]
