# Generated by Django 3.2.4 on 2021-06-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/net.png', upload_to='images'),
        ),
    ]
