# Generated by Django 3.2.4 on 2021-06-09 01:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_alter_post_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='PostModal',
        ),
    ]
