# Generated by Django 3.2.4 on 2021-06-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_post_postmodal'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodal',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
