# Generated by Django 3.2.4 on 2021-06-12 18:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_alter_postmodal_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostModal',
            new_name='Post',
        ),
    ]
