# Generated by Django 3.2.4 on 2021-06-19 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_image_post_banner_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pub_date',
            new_name='updated_date',
        ),
    ]
