# Generated by Django 3.2.4 on 2021-06-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
