# Generated by Django 3.2.4 on 2021-06-20 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_aboutuser_is_previously_logged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutuser',
            name='is_previously_logged',
        ),
    ]
